[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Domain redirects
[[redirects]]
  from = "https://www.cookiecomply.site/*"
  to = "https://cookiecomply.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://cookiecomply.site/*"
  to = "https://cookiecomply.site/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.cookiecomply.site/*"
  to = "https://cookiecomply.site/:splat"
  status = 301
  force = true

# API request handling
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Locale redirects
[[redirects]]
  from = "/"
  to = "/en/"
  status = 301

[[redirects]]
  from = "/:locale"
  to = "/:locale/"
  status = 301

# SPA routes for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
