# Конфигурация для Cloudflare Pages
name = "calculator"

# Указываем папку для сборки Pages (теперь это standalone)
pages_build_output_dir = ".next/standalone"

# Исключаем большие файлы из деплоя
[env.production]
name = "calculator"
vars = { ENVIRONMENT = "production" }

# Переменные окружения для превью
[env.preview]
name = "calculator-preview"
vars = { ENVIRONMENT = "preview" }

# Глобальные переменные окружения
[vars]
ENVIRONMENT = "development"
SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/T09CEV66EPN/B09CFBXDUGL/ACRW8p7RmKKalRIJrOti2"
