# Конфигурация для Cloudflare Pages
name = "calculator"

# Указываем папку для сборки Pages (теперь это standalone)
pages_build_output_dir = ".next/standalone"

# Исключаем большие файлы из деплоя
[env.production]
name = "calculator"
[env.production.vars]
ENVIRONMENT = "production"

# Переменные окружения для превью
[env.preview]
name = "calculator-preview"
[env.preview.vars]
ENVIRONMENT = "preview"

# Глобальные переменные окружения
[vars]
ENVIRONMENT = "development"
