# Configuration for Cloudflare Pages
name = "calculator"

# Specify build output directory for Pages (static export)
pages_build_output_dir = "out"

# Exclude large files from deployment
[env.production]
name = "calculator"
[env.production.vars]
ENVIRONMENT = "production"

# Environment variables for preview
[env.preview]
name = "calculator-preview"
[env.preview.vars]
ENVIRONMENT = "preview"

# Global environment variables
[vars]
ENVIRONMENT = "development"
