name = "calculator"
compatibility_date = "2024-01-01"

[build]
command = "npm run build:pages"

[build.upload]
format = "directory"

# Указываем папку dist для Cloudflare Pages
pages_build_output_dir = "dist"
