# Конфигурация для Cloudflare Pages
name = "calculator"

# Указываем папку с функциями
[functions]
directory = "functions"

# Конфигурация для Pages
[pages]
directory = ".next"

# Переменные окружения для продакшена
[env.production]
name = "calculator"
vars = { ENVIRONMENT = "production" }

# Переменные окружения для превью
[env.preview]
name = "calculator-preview"
vars = { ENVIRONMENT = "preview" }

# Глобальные переменные окружения
[vars]
ENVIRONMENT = "development"
