name = "calculator"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[build.upload]
format = "directory"

# Указываем папку out для статического экспорта
pages_build_output_dir = "out"
