name = "calculator"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
pages_build_output_dir = "dist"

[build.upload]
format = "directory"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
