# Конфигурация для Cloudflare Pages
name = "calculator"

# Указываем папку с собранными файлами
pages_build_output_dir = "out"

# Конфигурация для функций
[functions]
directory = "functions"

[env.production]
name = "calculator"

[env.preview]
name = "calculator-preview"
