# Configuration for Cloudflare Pages
name = "calculator2"

# Specify build output directory for Pages (static export)
pages_build_output_dir = "out"

# Environment variables for production
[env.production]
name = "calculator2"
[env.production.vars]
ENVIRONMENT = "production"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables for preview
[env.preview]
name = "calculator-preview"
[env.preview.vars]
ENVIRONMENT = "preview"

# Global environment variables
[vars]
ENVIRONMENT = "development"

# Compatibility settings
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
