[build]
command = "npm run build"
output_dir = "out"

[env.production]
name = "calculator"

[env.preview]
name = "calculator-preview"

[env.development]
name = "calculator-dev"

# Поддержка функций
[functions]
directory = "functions"
