# Конфигурация для Cloudflare Pages
name = "calculator"

# Указываем папку с собранными файлами
pages_build_output_dir = "dist"

[env.production]
name = "calculator"

[env.preview]
name = "calculator-preview"
